server:
  port: 8081

jwt:
  secret: mysecretkeytmkcmysecretkeytmkc123
  expiration: 3600000

spring:
  datasource:
    #edit later dont leave it hardcoded
    url: jdbc:postgresql://user-db:5432/userdb
    username: user
    password: password

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
